import { RiPlayFill } from "react-icons/ri";
import { GiClothes, GiPoliceOfficerHead } from "react-icons/gi";

export default [
  {
    title: "Retirar",
    icon: <GiClothes />,
    type: "category",
    action: "vestimenta",
    value: "vestimenta",
    category: "police",
  },
  {
    title: "Retirar máscara",
    icon: <RiPlayFill />,
    type: "action",
    action: "vestimenta",
    value: "rmascara",
    category: "vestimenta",
  },
  {
    title: "Retirar chápeu",
    icon: <RiPlayFill />,
    type: "action",
    action: "vestimenta",
    value: "rchapeu",
    category: "vestimenta",
  },
  {
    title: "Acessórios",
    icon: <GiPoliceOfficerHead />,
    type: "category",
    action: "acessorios",
    value: "acessorios",
    category: "police",
  },
  {
    title: "Colocar cone",
    icon: <RiPlayFill />,
    type: "action",
    action: "acessorios",
    value: "cone",
    category: "acessorios",
  },
  {
    title: "Deletar cone",
    icon: <RiPlayFill />,
    type: "action",
    action: "acessorios",
    value: "coned",
    category: "acessorios",
  },
  {
    title: "Colocar barreira",
    icon: <RiPlayFill />,
    type: "action",
    action: "acessorios",
    value: "barreira",
    category: "acessorios",
  },
  {
    title: "Deletar barreira",
    icon: <RiPlayFill />,
    type: "action",
    action: "acessorios",
    value: "barreirad",
    category: "acessorios",
  },
  {
    title: "Colocar spike",
    icon: <RiPlayFill />,
    type: "action",
    action: "acessorios",
    value: "spike",
    category: "acessorios",
  },
  {
    title: "Deletar spike",
    icon: <RiPlayFill />,
    type: "action",
    action: "acessorios",
    value: "spiked",
    category: "acessorios",
  },
  {
    title: "Retirar do veículo",
    icon: <RiPlayFill />,
    type: "action",
    action: "rv",
    category: "police",
  },
  {
    title: "Colocar no veículo",
    icon: <RiPlayFill />,
    type: "action",
    action: "cv",
    category: "police",
  },
  {
    title: "Prender",
    icon: <RiPlayFill />,
    type: "action",
    action: "prender",
    category: "police",
  },
  {
    title: "Retirar prisão",
    icon: <RiPlayFill />,
    type: "action",
    action: "tirarprisao",
    category: "police",
  },
];
